import { v4 as uuidv4 } from 'uuid';
import { BaseAIService } from '../AIServiceInterface';
import type {
  AIProvider,
  MealPlanRequest,
  MealPlanResponse,
  TrainingPlanRequest,
  TrainingPlanResponse,
  PlanAdjustmentRequest,
  MealEditRequest,
  MealEditResponse,
  ExpandInstructionsRequest,
  ExpandInstructionsResponse,
  RecipeVariationRequest,
  RecipeVariationResponse,
} from '../../../types/ai.types';
import type { MealPlan, TrainingPlan } from '../../../types';

export class MockProvider extends BaseAIService {
  readonly provider: AIProvider = 'mock';

  get isConfigured(): boolean {
    return true; // Mock provider doesn't need configuration
  }

  async generateMealPlan(request: MealPlanRequest): Promise<MealPlanResponse> {
    // Simulate API delay
    await new Promise((resolve) => setTimeout(resolve, 1000));

    const { userProfile, startDate, durationDays } = request;
    const endDate = new Date(startDate);
    endDate.setDate(endDate.getDate() + durationDays - 1);

    const dailyPlans = [];
    for (let i = 0; i < durationDays; i++) {
      const date = new Date(startDate);
      date.setDate(date.getDate() + i);

      dailyPlans.push({
        date,
        meals: [
          {
            id: `meal-${uuidv4()}`,
            type: 'breakfast' as const,
            scheduledTime: '07:00',
            recipe: {
              name: 'Mock Breakfast',
              description: 'A healthy mock breakfast',
              ingredients: [
                { name: 'Oats', amount: 50, unit: 'g', calories: 190 },
                { name: 'Banana', amount: 1, unit: 'medium', calories: 105 },
              ],
              instructions: ['Mix oats with water', 'Add sliced banana'],
              prepTime: 5,
              cookTime: 5,
              servings: 1,
              nutrition: {
                calories: 295,
                protein: 8,
                carbohydrates: 55,
                fat: 4,
              },
            },
          },
          {
            id: `meal-${uuidv4()}`,
            type: 'lunch' as const,
            scheduledTime: '12:00',
            recipe: {
              name: 'Mock Lunch',
              description: 'A balanced mock lunch',
              ingredients: [
                { name: 'Chicken Breast', amount: 150, unit: 'g', calories: 248 },
                { name: 'Brown Rice', amount: 100, unit: 'g', calories: 112 },
              ],
              instructions: ['Grill chicken', 'Cook rice'],
              prepTime: 10,
              cookTime: 20,
              servings: 1,
              nutrition: {
                calories: 360,
                protein: 42,
                carbohydrates: 23,
                fat: 6,
              },
            },
          },
          {
            id: `meal-${uuidv4()}`,
            type: 'dinner' as const,
            scheduledTime: '19:00',
            recipe: {
              name: 'Mock Dinner',
              description: 'A nutritious mock dinner',
              ingredients: [
                { name: 'Salmon', amount: 150, unit: 'g', calories: 280 },
                { name: 'Vegetables', amount: 200, unit: 'g', calories: 70 },
              ],
              instructions: ['Bake salmon', 'Steam vegetables'],
              prepTime: 10,
              cookTime: 20,
              servings: 1,
              nutrition: {
                calories: 350,
                protein: 38,
                carbohydrates: 12,
                fat: 18,
              },
            },
          },
        ],
        dailyNutrition: {
          calories: 1005,
          protein: 88,
          carbohydrates: 90,
          fat: 28,
        },
      });
    }

    const plan: MealPlan = {
      id: `meal-plan-${uuidv4()}`,
      userId: userProfile.id,
      name: `Mock ${durationDays}-Day Meal Plan`,
      startDate,
      endDate,
      dailyPlans,
      status: 'active',
      createdAt: new Date(),
    };

    return {
      plan,
      generationNotes: 'Generated by Mock Provider for testing',
    };
  }

  async generateTrainingPlan(
    request: TrainingPlanRequest
  ): Promise<TrainingPlanResponse> {
    // Simulate API delay
    await new Promise((resolve) => setTimeout(resolve, 1000));

    const { userProfile, startDate, durationWeeks } = request;
    const endDate = new Date(startDate);
    endDate.setDate(endDate.getDate() + durationWeeks * 7 - 1);

    const sessions = [];
    for (let week = 0; week < durationWeeks; week++) {
      for (let day = 0; day < 3; day++) {
        // 3 sessions per week
        const date = new Date(startDate);
        date.setDate(date.getDate() + week * 7 + day * 2);

        sessions.push({
          id: `session-${uuidv4()}`,
          date,
          name: `Mock Workout ${week + 1}.${day + 1}`,
          type: 'strength' as const,
          duration: 45,
          targetIntensity: 'moderate' as const,
          scheduledTime: '18:00',
          exercises: [
            {
              id: `exercise-${uuidv4()}`,
              name: 'Push-ups',
              description: 'Classic push-up exercise',
              type: 'strength' as const,
              muscleGroups: ['chest', 'triceps', 'shoulders'],
              equipment: [],
              sets: 3,
              reps: 12,
              restBetweenSets: 60,
              intensity: 'moderate' as const,
              instructions: ['Start in plank position', 'Lower body', 'Push back up'],
            },
          ],
          warmup: [],
          cooldown: [],
          estimatedCalories: 300,
        });
      }
    }

    const plan: TrainingPlan = {
      id: `training-plan-${uuidv4()}`,
      userId: userProfile.id,
      name: `Mock ${durationWeeks}-Week Training Plan`,
      startDate,
      endDate,
      sessions,
      status: 'active',
      createdAt: new Date(),
      focusAreas: ['strength', 'general fitness'],
    };

    return {
      plan,
      generationNotes: 'Generated by Mock Provider for testing',
    };
  }

  async adjustPlan(
    request: PlanAdjustmentRequest
  ): Promise<MealPlanResponse | TrainingPlanResponse> {
    if (request.planType === 'meal') {
      return await this.generateMealPlan({
        userProfile: request.userProfile,
        startDate: new Date(),
        durationDays: 7,
        adjustmentContext: {
          adherenceAnalysis: request.adherenceAnalysis,
          specificRequests: request.specificRequests,
        },
      });
    } else {
      return await this.generateTrainingPlan({
        userProfile: request.userProfile,
        startDate: new Date(),
        durationWeeks: 4,
        adjustmentContext: {
          adherenceAnalysis: request.adherenceAnalysis,
          specificRequests: request.specificRequests,
        },
      });
    }
  }

  async editMeal(request: MealEditRequest): Promise<MealEditResponse> {
    // Simulate API delay
    await new Promise((resolve) => setTimeout(resolve, 1500));

    const { meal } = request;

    // Return the meal with "(Edited)" suffix to simulate editing
    const editedMeal = {
      ...meal,
      recipe: {
        ...meal.recipe,
        name: `${meal.recipe.name} (Edited)`,
        description: `${meal.recipe.description} - Modified based on your request.`,
      },
    };

    return {
      meal: editedMeal,
      editNotes: 'Edited by Mock Provider for testing',
    };
  }

  async expandInstructions(_request: ExpandInstructionsRequest): Promise<ExpandInstructionsResponse> {
    // Simulate API delay
    await new Promise((resolve) => setTimeout(resolve, 800));

    return {
      instructions: {
        quick: ['Mix ingredients', 'Cook as directed', 'Serve hot'],
        standard: [
          'Prepare all ingredients',
          'Heat pan/oven to required temperature',
          'Cook ingredients according to method',
          'Check for doneness',
          'Season to taste',
          'Serve immediately',
        ],
        detailed: [
          'Gather and measure all ingredients precisely',
          'Preheat cooking equipment to specified temperature',
          'Prepare ingredients (wash, chop, etc.)',
          'Begin cooking process with proper technique',
          'Monitor temperature and timing carefully',
          'Adjust seasoning throughout cooking',
          'Check for visual and tactile doneness cues',
          'Remove from heat at optimal time',
          'Let rest if needed',
          'Plate attractively and serve',
        ],
      },
      notes: 'Mock expanded instructions for testing',
    };
  }

  async generateRecipeVariations(request: RecipeVariationRequest): Promise<RecipeVariationResponse> {
    // Simulate API delay
    await new Promise((resolve) => setTimeout(resolve, 1200));

    const { recipe, variationCount } = request;
    const variations = [];

    for (let i = 0; i < variationCount; i++) {
      variations.push({
        id: `recipe-${uuidv4()}`,
        name: `${recipe.name} (Variation ${i + 1})`,
        description: `${recipe.description} - Modified version`,
        ingredients: recipe.ingredients,
        instructions: recipe.instructions,
        instructionLevel: recipe.instructionLevel || 'quick',
        prepTime: recipe.prepTime,
        cookTime: recipe.cookTime,
        servings: recipe.servings,
        nutrition: {
          calories: recipe.nutrition.calories + (i * 10 - 10),
          protein: recipe.nutrition.protein + (i - 1),
          carbohydrates: recipe.nutrition.carbohydrates + (i - 1),
          fat: recipe.nutrition.fat + (i - 1),
        },
        variantType: 'variation' as const,
        variantNotes: `Mock variation ${i + 1}: Changed ingredient ${i + 1}`,
      });
    }

    return {
      variations,
      notes: 'Mock recipe variations for testing',
    };
  }

  async healthCheck(): Promise<boolean> {
    return true;
  }
}
